const forms = require("@tailwindcss/forms");
const containerQueries = require("@tailwindcss/container-queries");

module.exports = {
  darkMode: "class",
  content: ["./index.html", "./export.html", "./history.html", "./*.js"],
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#632b2d",
        "on-error-container": "#671200",
        "inverse-surface": "#0e0e0e",
        "tertiary-container": "#dbc6f6",
        "secondary-dim": "#4b5737",
        surface: "#fbf9f8",
        "tertiary-fixed-dim": "#ccb9e8",
        "surface-variant": "#e3e2e2",
        "on-tertiary": "#fef7ff",
        "on-secondary": "#f0ffd3",
        "on-primary-fixed-variant": "#6e3435",
        "surface-container-high": "#e9e8e7",
        "surface-container-low": "#f5f3f3",
        "on-tertiary-fixed-variant": "#574770",
        "on-primary-fixed": "#491719",
        "secondary-fixed": "#e5f4c9",
        "on-primary": "#fff7f6",
        "on-error": "#fff7f6",
        "surface-container-highest": "#e3e2e2",
        "surface-container": "#efeded",
        "tertiary-dim": "#5c4c74",
        "primary-container": "#fdabab",
        "primary-fixed": "#fdabab",
        background: "#fbf9f8",
        secondary: "#576342",
        "surface-dim": "#dbdad9",
        "surface-bright": "#fbf9f8",
        "inverse-on-surface": "#9e9c9c",
        "secondary-container": "#e5f4c9",
        "outline-variant": "#b2b2b1",
        "on-tertiary-container": "#4e3e66",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#d7e5bb",
        "on-secondary-fixed-variant": "#5a6745",
        "primary-dim": "#7f4142",
        "on-background": "#323233",
        "inverse-primary": "#fdabab",
        "on-surface-variant": "#5f5f5f",
        "error-container": "#fa7150",
        outline: "#7b7b7b",
        error: "#aa371c",
        "primary-fixed-dim": "#ee9e9e",
        "surface-tint": "#8d4d4d",
        "on-secondary-fixed": "#3e4a2b",
        tertiary: "#685881",
        "on-surface": "#323233",
        primary: "#8d4d4d",
        "on-tertiary-fixed": "#3a2b51",
        "error-dim": "#821a01",
        "tertiary-fixed": "#dbc6f6",
        "on-secondary-container": "#505d3c",
      },
      fontFamily: {
        headline: ["Noto Serif", "Songti SC", "serif"],
        playfair: ["Playfair Display", "serif"],
        cormorant: ["Cormorant Garamond", "serif"],
        body: ["Manrope", "PingFang SC", "sans-serif"],
        label: ["Manrope", "PingFang SC", "sans-serif"],
      },
    },
  },
  plugins: [forms, containerQueries],
};
